/**
 * Pre-bundled Tarot Card Assets
 *
 * This file manages static card images that are bundled with the app.
 * Cards in this bundle load instantly (no network/generation needed).
 *
 * USAGE:
 * ------
 * To generate cards, run one of:
 *   npm run generate:cards -- --card 0     # Generate The Fool only
 *   npm run generate:cards:major           # Generate all 22 Major Arcana
 *   npm run generate:cards:all             # Generate all 78 cards
 *   npm run generate:cards:missing         # Generate only missing cards
 *
 * After generating, this file is auto-updated with require() statements.
 *
 * PRIORITY ORDER:
 * ---------------
 * 1. Bundled assets (this file) - instant load
 * 2. Filesystem (user-generated at runtime)
 * 3. AI generation (on-demand)
 *
 * AUTO-GENERATED: This file is auto-generated by scripts/generate-assets.ts
 * DO NOT EDIT MANUALLY - Run the generation script to update
 */

export type CardAssetMap = {
  [cardId: number]: ReturnType<typeof require> | null;
};

// Card back image (bundled)
// When generated, this becomes: require('./card-back.png')
export const cardBackAsset: ReturnType<typeof require> | null = null;

/**
 * Individual card assets map
 *
 * When a card is generated and bundled, an entry is added like:
 *   0: require('./card-0.png'), // The Fool
 *
 * Card ID Reference:
 * - 0-21: Major Arcana (The Fool through The World)
 * - 22-35: Wands (Ace through King)
 * - 36-49: Cups (Ace through King)
 * - 50-63: Swords (Ace through King)
 * - 64-77: Pentacles (Ace through King)
 */
export const cardAssets: CardAssetMap = {
  // === MAJOR ARCANA (0-21) ===
  0: require('./card-0.png'), // The Fool
  // 1: require('./card-1.png'), // The Magician
  // 2: require('./card-2.png'), // The High Priestess
  // ... (run generate:cards:major to populate)

  // === MINOR ARCANA - WANDS (22-35) ===
  // 22: require('./card-22.png'), // Ace of Wands
  // ... (run generate:cards:all to populate)

  // === MINOR ARCANA - CUPS (36-49) ===
  // === MINOR ARCANA - SWORDS (50-63) ===
  // === MINOR ARCANA - PENTACLES (64-77) ===
};

/**
 * Check if a card has a bundled asset available
 */
export const hasBundledAsset = (cardId: number): boolean => {
  return cardId in cardAssets && cardAssets[cardId] !== null;
};

/**
 * Get the bundled asset for a card
 * Returns null if the card isn't bundled
 */
export const getBundledAsset = (cardId: number): ReturnType<typeof require> | null => {
  return cardAssets[cardId] ?? null;
};

/**
 * Get count of cards that have bundled assets
 */
export const getBundledCardCount = (): number => {
  return Object.values(cardAssets).filter(asset => asset !== null).length;
};

/**
 * Check if the card back is bundled
 */
export const hasCardBackAsset = (): boolean => {
  return cardBackAsset !== null;
};

// Total cards in a standard tarot deck
export const TOTAL_CARDS = 78;
